### ISSUE TITLE
Automatically refresh invoice payment

### ISSUE THREAD

**Issue by sgeisler** [agora-org/agora#142]
Currently it seems like the invoice page has to be reloaded manually after payment. A simple

```html
<meta http-equiv="refresh" content="5;url=/invoice/sdfjklsdfjskldfjlsk" />
```

might do the trick. The invoice page seems lightweight enough to do that. Later it could be replaced with e.g. websockets. Alternatively long-polling might also work (without JS).

**Comment by soenkehahn** [comment]
Thanks for opening the issue!

We thought about this and think it'd be confusing if the invoice page just disappeared and switched over to the paid file. For example imagine a user has the invoice page open in a browser in some background tab when paying the invoice. They won't even notice that the file will be displayed, which -- depending on file type -- could be weird.

The current behavior is still really bad, since the invoice doesn't even give users any indication what to do after paying the invoice. We put up #173 to make it a bit better, with a button that reloads the page and instructions at the bottom.

We think in the future a better version would have a button that is greyed out as long as the invoice isn't paid and activates (without user interaction) once the invoice is paid.
