### ISSUE TITLE
Support for Rust 1.48?

### ISSUE THREAD

**Issue by Kixunil** [agora-org/agora#207]
Would it be possible to support Rust 1.48 which is available in Debian Bullseye? I'd like to eventually package this project as a Debian package so this is required.

**Comment by casey** [comment]
> Would it be possible to support Rust 1.48 which is available in Debian Bullseye? I'd like to eventually package this project as a Debian package so this is required.

Definitely. We just merged #208, which switches our CI pipeline to use Rust 1.48 and removes some use of post 1.48 features. Let us know if there's anything else we can do to help!

**Comment by casey** [comment]
We were just updating our dependencies, and it like we're running into trouble with some dependencies which have an MSRV greater than 1.48.0. One example is `rustls` which has an MSRV of 1.52.1.

This is a bit concerning, since `agora` is potentially security-critical software, since it handles money, valuable files, and will potentially be co-located with bitcoin and lightning nodes, and might not be well-sandboxed by operators.

When you mentioned that you were interested in packaging `agora` for Debian Bullseye, would that make it into a release that users could install with `apt-get agora`, or would it be a `.deb` file that they would have to install manually?

We were under the impression that new packages don't automatically make it into existing Debian releases, so packaging `agora` now would make it into the next major debian release, but not the current Bullseye release, or future Bullseye point-releases.

**Comment by casey** [comment]
> I meant I want to package it withing [Cryptoanarchy Debian Repository](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder), sorry for confusion. :(

Gotcha. No worries at all! We'd obviously like it packaged everywhere possible, so that would still be cool.

> If `rustls` is security-critical software maybe it should keep their MSRV reasonably low? Probably worth asking. I wonder what the other dependencies are.

I believe it's an issue with mis-compilations by pre-1.52.1 Rust:

https://github.com/rustls/rustls/blob/05172d056ea77cd5d67edf5055909168a907f08b/.github/workflows/build.yml#L19

We don't have a pressing need to break compatibility with 1.48.0 at the moment, but I think there's a good chance that we'll run into a dependency that can't easily be made to work with 1.48. I think if that happens, we'll probably have to break compatibility with 1.48. So just be aware that might happen. We'll try to keep you informed if it does though.
