### ISSUE TITLE
Improve CI Caching Strategy

### ISSUE THREAD

**Issue by casey** [agora-org/agora#92]
@terror and I ran into issues with our GitHub Actions cache after we added `resolver = "2"` to our `Cargo.toml` file. The issue turned out to be that we were getting a cache hit because the cache key hadn't changed, but the cache wasn't useful, presumably because we hadn't updated the `Cargo.lock` file in the repo, so every build was:

- Getting a cache hit and loading the cache
- Building slowly, because the cache wasn't useful
- *Not* saving new artifacts to the cache, because the cache action never updates the cache when there's a cache hit

The simple fix was to invalidate the cache.

However, after thinking about it for a while, we came up with an alternative caching strategy. I wanted to make an issue in Agora, both to get your feedback to make sure there isn't wrong with the alternative strategy, and also to propose using it for Agora CI, since it seems like it has better behavior than what we're using.

The new strategy was added in https://github.com/quwue/quwue/pull/38, and the new cache step looks like this:

```
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-
```

The behavior of actions/cache is a bit complicated, so let's go through what happens step-by-step, if we were to make this change, run it on a PR branch, merge it to master, and then open a new, unrelated PR.

### Initial PR
- Cache miss, because `${{ github.sha }}` is different for every commit
- Restore fails, because no cache entries exist that match `${{ runner.os }}-`
- Slow build because no artifacts were restored
- Build artifacts stored to full cache key

### Merge to master
- Cache miss, because `${{ github.sha }}` is different for every commit
- Restore fails, because no cache entries exist that match `${{ runner.os }}-`
- Slow build because no artifacts were restored
- Build artifacts stored to full cache key

### First commit on PR on non-master branch
- Cache miss, because `${{ github.sha }}` is different for every commit
- Restore succeeds, because default branch (`master` in our case) has cache entry that is a partial match for  `${{ runner.os }}-`
- Fast build because useful artifacts were restored
- Build artifacts stored to full cache key

### New commit on PR on non-master branch
- Cache miss, because `${{ github.sha }}` is different for every commit
- Restore succeeds, because PR branch has cache entry that is a partial match for  `${{ runner.os }}-` from previous commit
- Fast build because useful artifacts were restored
- Build artifacts stored to full cache key

### Merge new PR to master
- Cache miss, because `${{ github.sha }}` is different for every commit
- Restore succeeds, because master branch has cache entry that is a partial match for  `${{ runner.os }}-` from initial PR
- Fast build because useful artifacts were restored
- Build artifacts stored to full cache key

## Pros
- Builds are always faster, because the cache is updated every time, instead of just when a lockfile changes
- Won't run into situations where the cache isn't useful because a lockfile didn't change, but the cache should have been updated

## Cons
- The cache will be stored every time, which is slow on windows (~3 minutes)
- Will create cache entry on every commit, instead of just on commits where `Cargo.lock` changes. The GitHub Actions docs says that repositories are limited to 5GiB of caches, which is low. Each cache entry is 600 MiB, so we'd only be able to store about 10 cache entries. If GitHub actions evicts cache entires in a bad order (Docs say "older caches will be evicted based on when the cache was last accessed") we could have slow builds
- Since cache is always restored, cache could grow, because we never outright delete the `target` dir. However, this is ameliorated by the 5GiB limit, so if the cache gets large, presumably it'll  just get evicted

What do you think about the two strategies? 

@soenkehahn

**Comment by soenkehahn** [comment]
Good question. My initial thought is this: It seems like the github actions caches are supposed to be used this way: Hashes of all files that have an influence on which dependencies are built should be in the cache key. And then whenever those files change, it rebuilds everything. In that vein maybe we should add a hash of the `Cargo.toml` file to the cache key. This will cause a few cache invalidations that aren't necessary, in case the `Cargo.toml` file changes without changing the installed dependencies. But maybe being more conservative when invalidating caches is just fine here. We should consider putting `rust-toolchain` in there too.

With the `restore-keys` set up how you described I would be a bit concerned:

- Overall it seems a bit of a complicated strategy. So if the caches misbehave it's not as easy to figure out what happened.
- Having the caches contain unused dependencies in their `target` directory seems weird and slightly concerning. Although I can't think of a situation that would be that bad.
- I would be worried that, since the caching behavior is more complicated, we would be tempted to just invalidate the caches manually whenever there's something fishy going on.

Overall it's a bit speculation. I think trying this out is the only way to know for sure whether this would work well.

Another note: I think the initial problem, that we have cache hits and builds are still slow caused by the `resolver` setting is also fairly exceptional. So maybe the best solution is to just bump the `CACHE_KEY` and move on.

**Comment by casey** [comment]
> Good question. My initial thought is this: It seems like the github actions caches are supposed to be used this way: Hashes of all files that have an influence on which dependencies are built should be in the cache key. And then whenever those files change, it rebuilds everything.

I think that might not actually be the case. I originally thought that, based on the suggested cache configuration for Rust:

```yaml
- uses: actions/cache@v2
  with:
    path: |
      ~/.cargo/bin/
      ~/.cargo/registry/index/
      ~/.cargo/registry/cache/
      ~/.cargo/git/db/
      target/
    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
```

However, the suggested cache configuration for other languages uses `restore-keys` in the way I used them:

```yaml
- uses: actions/cache@v2
  with:
    path: ~/.npm
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-
```

After reading issues, I think perhaps the reason this isn't done for Rust is because the cache gets too large otherwise.

> Another note: I think the initial problem, that we have cache hits and builds are still slow caused by the `resolver` setting is also fairly exceptional. So maybe the best solution is to just bump the `CACHE_KEY` and move on.

I think this is reasonable. I think we could run into problems with the caches getting to big, or expiring frequently, which would be hard to notice or diagnoce. I'm going to go ahead and close this.
