### ISSUE TITLE
Join forces on LND tonic client?

### ISSUE THREAD

**Issue by Kixunil** [agora-org/agora#99]
Basically what I asked at https://github.com/briansmith/webpki/issues/114 - can we benefit from maintaining a single LND crate?

Regarding security it's a shame briansmith didn't explain it better before locking but I personally suspect that as a maintainer of **PKI** crate he has a different threat model than us. The `webpki` crate is probably not the right place but would love to talk to some TLS people about security of LND RPC.

BTW your project has very special name and uses LND which is very interesting for me but I don't understand how LND is related with file sharing. Would be nice to explain in the README. :)

**Comment by casey** [comment]
Hi Kinuxil! Our current LND client implementation is limited and tailored to the needs of the project, and would probably not be useful to anyone else, so we're hesitant to try to make it more broadly useful. Although there's definitely a hole in the ecosystem, we're probably going to keep working on our LND client implementation and not think about publishing it for now.

> BTW your project has very special name and uses LND which is very interesting for me but I don't understand how LND is related with file sharing. Would be nice to explain in the README. :)

It's definitely a little confusing at the moment! Agora should eventually let people sell files online for Lightning payments, but since it only has file listing and downloads right now, we don't mention anything about payments, so the name Agora doesn't make sense with the current readme.

**Comment by Kixunil** [comment]
Maybe you could use my `tonic_lnd` crate? Are there any requirements you have that are not yet implemented? I could add a few small things. If the difference is too huge then it's probably best to keep them separate at least for now, of course.

I'm looking forward to see your project ready, good luck!

**Comment by casey** [comment]
There are a few minor differences. We're using OpenSSL instead of a custom cert verifier, and we're using a lower-level interface that takes the macaroon and TLS certificate as bytes (so the consumer of the library is responsible from reading them off of disk). (You can check out the the OpenSSL code [here](https://github.com/agora-org/agora/blob/master/lnd-client/src/grpc_service.rs), which might be useful if you want to support it, in addition to or instead of `rustls`.) But the main thing is that I think the crate is likely to be pretty small, with the two parts being the auto-generated proto bindings, and the custom `Client` interface. We could hypothetically have a shared proto-bindings crate, but since it's not that much code, the coordination overhead might not make it worth it to share.

**Comment by casey** [comment]
> I'm looking forward to see your project ready, good luck!

And thank you, we need it!

**Comment by Kixunil** [comment]
> but since it's not that much code, the coordination overhead might not make it worth it to share.

True, let's keep loose cooperation now by just getting inspired from each other. :)

I have specifically avoided taking the bytes to discourage people from caching LND connection details. Such caching was causing problems in practical applications. (LND changed something and data got invalidated.) Perhaps something to put in the docs of your project.
